spring:
  datasource:
    url: ${AWS_RDS_MYSQL_URL}
    username: ${AWS_RDS_MYSQL_USERNAME}
    password: ${AWS_RDS_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${AWS_ELASITCACHE_REDIS_URL}
      port: ${AWS_ELASITCACHE_REDIS_PORT}

    mongodb:
      uri: ${ATLAS_MONGO_URI}
      database: ${ATLAS_MONGO_DATABASE}

cloud:
  aws:
    credentials:
      instance-profile: false
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

    s3:
      bucket: ${AWS_BUCKET_NAME}

    region:
      auto: false
      static: ap-northeast-2

    stack: false

    cloudfront-path: ${AWS_FILE_PATH}

ssh:
  host: ${SSH_HOST}
  port: ${SSH_PORT}
  user: ${SSH_USER}
  private_key_path: ${SSH_PRIVATE_KEY_PATH}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expire: ${JWT_ACCESS_EXPIRE}

  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expire: ${JWT_REFRESH_EXPIRE}
    ttl:
      seconds: ${JWT_REFRESH_TTL_SECONDS}
