spring:
  datasource:
    url: ${DEV_MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}

  data:
    redis:
      host: ${AWS_ELASITCACHE_REDIS_URL}
      port: ${AWS_ELASITCACHE_REDIS_PORT}

    mongodb:
      uri: ${ATLAS_MONGO_URI}
      database: ${ATLAS_MONGO_DATABASE}
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

cloud:
  aws:
    credentials:
      instance-profile: false
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

    s3:
      bucket: ${AWS_BUCKET_NAME}

    region:
      auto: false
      static: ap-northeast-2

    stack: false

    cloudfront-path: ${AWS_FILE_PATH}

    rds:
      database:
        url: ${AWS_RDS_MYSQL_URL}
        port: ${AWS_RDS_MYSQL_PORT}

ssh:
  host: ${SSH_HOST}
  port: ${SSH_PORT}
  user: ${SSH_USER}
  private_key_path: ${SSH_PRIVATE_KEY_PATH}

jwt:
  access:
    secret: ${DEV_JWT_ACCESS_SECRET}
    expire: ${DEV_JWT_ACCESS_EXPIRE}

  refresh:
    secret: ${DEV_JWT_REFRESH_SECRET}
    expire: ${DEV_JWT_REFRESH_EXPIRE}
    ttl:
      seconds: ${DEV_JWT_REFRESH_TTL_SECONDS}

api:
  naver:
    client-id: ${NAVER_API_ID}
    client-secret: ${NAVER_API_SECRET}
